repos:
  - repo: local
    hooks:
      - id: validate-workflows
        name: validate-workflows
        entry: python src/scripts/validate_workflows.py
        language: python
        files: ^\.github/workflows/.*\.yml$
        pass_filenames: false
