version: '3.8'

services:
  blazegraph:
    image: lyrasis/blazegraph:2.1.5
    ports:
      - "9999:9999"
    volumes:
      - blazegraph-data:/data
    environment:
      - BLAZEGRAPH_OPTS=-Dbigdata.propertyFile=/data/RWStore.properties
    restart: always

volumes:
  blazegraph-data:
